"""add warehouse user authorization

Revision ID: 851cedfce124
Revises: a97d47e53534
Create Date: 2026-10-06 10:55:08.860750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '851cedfce124'
down_revision: Union[str, Sequence[str], None] = 'a97d47e53534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'warehouse_id', name='uq_user_warehouse')
    )
    op.create_index(op.f('ix_warehouse_users_id'), 'warehouse_users', ['id'], unique=False)
    op.create_index(op.f('ix_warehouse_users_user_id'), 'warehouse_users', ['user_id'], unique=False)
    op.create_index(op.f('ix_warehouse_users_warehouse_id'), 'warehouse_users', ['warehouse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warehouse_users_warehouse_id'), table_name='warehouse_users')
    op.drop_index(op.f('ix_warehouse_users_user_id'), table_name='warehouse_users')
    op.drop_index(op.f('ix_warehouse_users_id'), table_name='warehouse_users')
    op.drop_table('warehouse_users')
    # ### end Alembic commands ###
