"""create return management

Revision ID: ba72af04a0bf
Revises: 738ee3201835
Create Date: 2026-10-06 12:52:04.674605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba72af04a0bf'
down_revision: Union[str, Sequence[str], None] = '738ee3201835'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_assignments_assigned_at'), 'order_assignments', ['assigned_at'], unique=False)
    op.create_index(op.f('ix_order_assignments_assigned_by'), 'order_assignments', ['assigned_by'], unique=False)
    op.create_index(op.f('ix_order_assignments_assigned_to'), 'order_assignments', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_order_assignments_id'), 'order_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_order_assignments_order_id'), 'order_assignments', ['order_id'], unique=False)
    op.create_table('return_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('processed_by', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_return_requests_customer_id'), 'return_requests', ['customer_id'], unique=False)
    op.create_index(op.f('ix_return_requests_id'), 'return_requests', ['id'], unique=False)
    op.create_index(op.f('ix_return_requests_order_id'), 'return_requests', ['order_id'], unique=False)
    op.create_index(op.f('ix_return_requests_order_item_id'), 'return_requests', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_return_requests_status'), 'return_requests', ['status'], unique=False)
    op.drop_constraint(op.f('uq_orders_order_number'), 'orders', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_orders_order_number'), 'orders', ['order_number'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_return_requests_status'), table_name='return_requests')
    op.drop_index(op.f('ix_return_requests_order_item_id'), table_name='return_requests')
    op.drop_index(op.f('ix_return_requests_order_id'), table_name='return_requests')
    op.drop_index(op.f('ix_return_requests_id'), table_name='return_requests')
    op.drop_index(op.f('ix_return_requests_customer_id'), table_name='return_requests')
    op.drop_table('return_requests')
    op.drop_index(op.f('ix_order_assignments_order_id'), table_name='order_assignments')
    op.drop_index(op.f('ix_order_assignments_id'), table_name='order_assignments')
    op.drop_index(op.f('ix_order_assignments_assigned_to'), table_name='order_assignments')
    op.drop_index(op.f('ix_order_assignments_assigned_by'), table_name='order_assignments')
    op.drop_index(op.f('ix_order_assignments_assigned_at'), table_name='order_assignments')
    op.drop_table('order_assignments')
    # ### end Alembic commands ###
